### ISSUE TITLE
listen to when a new layer is created

### ISSUE THREAD

**Issue by vogis** [codeofsumit/leaflet.pm#101]
Hi,

I'm currently trying to configure a function to save the draw data to a geojson file, however the markers are not integrate to the function with "map.on('pm:create', function(e) {//...});".
I noticed that it's possible with other objects like line and polygon.

Do you have a solution for this?
Thanks

**Comment by codeofsumit** [comment]
@vogis hi there,

yourMap.on('pm:create', function(e) {
    alert('pm:create event fired. See console for details');
    console.log(e);
});

should also fire when a marker is created.

Do you mind creating a demo case, like JSfiddle, with your usecase where it doesn't work?
If we find a bug or a missing feature on that part, I can fix it this week.

**Comment by vogis** [comment]
Hi,
Thank for your reply.
Here the link to the JSfiddle where you find a layer with the name draw.
When I draw a line or a polygon, objects are added to the draw layer however the markers are not added to the layer. same effect for delete function.

https://jsfiddle.net/hhp61bnb/2/

**Comment by codeofsumit** [comment]
ah I see where the problem is.
If you look at the console output from line 36 (JavaScript) of your JSFiddle, you'll see this:
![image](https://cloud.githubusercontent.com/assets/2399810/20636338/91f0de56-b36b-11e6-987e-63ce565a3702.png)

The markers aren't named "layer", they're named "marker" in the event.

But I think I should name them "layer" as well. Do you mind working with "marker" for now? I'll add the "layer" property to marker create/delete events as well in the next release. I think I have to clean up the naming across the plugin, because in leaflet pretty much EVERYTHING is a layer.

**Comment by vogis** [comment]
Yes, of course I can work with the marker while waiting for the next release.
Thanks

**Comment by codeofsumit** [comment]
I did not forget this. I'm just very busy right now. Hopefully I'll be able to do this this weekend

**Comment by vogis** [comment]
Thank you for fixing the issue.

**Comment by codeofsumit** [comment]
@vogis of course! Sorry that it took longer than expected.
