### ISSUE TITLE
How to disable entire polygon dragging?

### ISSUE THREAD

**Issue by leekosal** [codeofsumit/leaflet.pm#116]
When I edit a polygon, and i try to move entire polygon and with just very small move of mouse, entire polygon disappears. it seems it goes move to far. 

How can i just disable moving entire polygon. Thanks

**Comment by codeofsumit** [comment]
Can you build your case on jsfiddle.com so I can reproduce this issue? Then, I can fix it asap

**Comment by leekosal** [comment]
thanks. I have sent the code to your outlook email. Maybe easier to check.

**Comment by codeofsumit** [comment]
thank you for the demo. The issue is with Leaflet Measure Path.
I opened an issue [here](https://github.com/ProminentEdge/leaflet-measure-path/issues/11) about it and proposed a fix via [this Pullrequest](https://github.com/ProminentEdge/leaflet-measure-path/pull/12). If the maintainer merges it the problem is gone.

Until then, you can edit `leaflet-measure-path.js` in your project yourself by changing this:
https://github.com/ProminentEdge/leaflet-measure-path/pull/12/files

Hope this helps.

**Comment by leekosal** [comment]
thank you so much.
