### ISSUE TITLE
Pass Options of enable & enableDraw to Toolbar buttons.

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/leaflet.pm#117]
As discussed in #116 we need a way to set options of `enable` and `enableDraw` for the toolbar buttons as well.

**Comment by willvincent** [comment]
This really shouldn't have been closed. This definitely is still an issue.

While you can programmatically call the `enable()` method and pass options to it, and similarly for `enableDraw()`, there is not a way to do so in configuration for the toolbar buttons themselves.

#233 added documentation of how to pass options when programatically calling the `enableDraw()` method.  But there is no way I can see, other than reaching into the object after the button has been set visible in the toolbar, to change the _behavior_ or options of edit mode button.

What I found necessary was having to explicitly reach deep into the object and override the `afterclick()` method of the editMode button's options:

```
    this.map.pm.Toolbar.buttons.editMode.options.afterClick = () => {
      this.map.pm.toggleGlobalEditMode({
        allowSelfIntersection: false,
        snapDistance: 10,
      });
    };
```

This is all fine and well, but if this is necessary then instead of just true/false `addControls()` should allow for passing alternative options to override/combine with the internal defaults at play on the toolbar buttons.

Maybe I missed it in the docs, but it doesn't appear to be possible.

**Comment by codeofsumit** [comment]
Options passed via enableDraw should be preserved for edit mode of the toolbar but nonetheless, I’ll make this a feature request as passing more options in addControls is a good idea. Please upvote

**Comment by Falke-Design** [comment]
@codeofsumit can we say that this is now implemented with the new toolbar functions?

**Comment by codeofsumit** [comment]
@willvincent can you confirm that the latest release solves this issue for you?
