### ISSUE TITLE
Add a hint marker when drawing a marker

### ISSUE THREAD

**Issue by gouroujo** [codeofsumit/leaflet.pm#130]
Hi there !
What do you think about adding a marker hint when you draw a marker on the map?
It could be nice to have the same UX you have when drawing a polygon/polyline.
The white DivIcon is pretty nice and easly customizable.
Moreover, you could also add snapping when drawing a marker with this feature.

It is something you have planned to add ?

cheers

**Comment by codeofsumit** [comment]
@gouroujo snapping while drawing is already implemented. The marker on the cursor is also there, but hidden because it created some specific problems. Let me check it again and see if I can make it work. I'll update this issue when I find problems that prevent me from adding it to the library.

What I could think of is an option for drawing that enables/disables the cursor marker.

In the meantime, you could add
```
.cursor-marker {
    display: block !important;
}
```

to your CSS and make it visible again.

![image](https://cloud.githubusercontent.com/assets/2399810/22696538/a2397878-ed4e-11e6-91a8-de8f7fb5584b.png)
(that's during draw)


Let me know if that works!

**Comment by codeofsumit** [comment]
wops just saw your updated title. You mean during marker draw? Ok that's not in here but yes, this makes sense. I'll implement it this week!

**Comment by codeofsumit** [comment]
@gouroujo gotta test a little more but it's almost there
![snappable_markers](https://cloud.githubusercontent.com/assets/2399810/22700655/ae695bc4-ed5b-11e6-98b9-a944d0ceee51.gif)

**Comment by codeofsumit** [comment]
if you want to try it out, here's the PR:
https://github.com/codeofsumit/leaflet.pm/pull/131

I'll leave it open until tomorrow. If I (or anybody else) doesn't find bugs until then, I'll merge and publish a new release.

**Comment by gouroujo** [comment]
Hi @codeofsumit, thanks for you work that was exactly what I'm thinking of. Your PR looks good to me.

**Comment by codeofsumit** [comment]
@gouroujo it's released now in version 0.15.0
