### ISSUE TITLE
Custom remove event for pm

### ISSUE THREAD

**Issue by GeoTob** [codeofsumit/leaflet.pm#162]
I propose to add a `pm:remove` event similar to the existing `pm:create`. 

Currently Leaflet's `layerremove` event is the only way to listen to layer deletions. Problem is it's fired quite frequently when pm destroys its helper layers after each draw. The `pm:remove` event would fire only after the user has deleted a layer from the map, so that we can attach custom logic to handle user interaction.

For now I have patched `removeLayer` in `L.PM.Map` like below, but there might be a better place for this?

```js
removeLayer(e) {
  const layer = e.target;
  const map = layer._map;
  if(!layer._layers && !layer.pm.dragging()) {
    layer.remove();
    map.fire('pm:remove')
  }
},
```

**Comment by codeofsumit** [comment]
`Currently Leaflet's layerremove event is the only way to listen`

This 👆  was exactly why I haven't added `pm:remove` but you're totally right - it fires for all the helpers and this marks a problem. Thanks for pointing it out.
I will implement this.

**Comment by codeofsumit** [comment]
@GeoTob turns out, it's not that easy.

1. Could you provide a JSFiddle where the remove event is fired for helpers?
2. The workaround you provided is good but if someone removes a layer via code, it wouldn't fire.
I want `pm:remove` to be fired whenever a layer is removed (doesn't matter how).

Currently I'm trying to distinguish my helper layers from the actual layers of the map - but somehow I can't find a case where the helpers are still on the map during the remove event (I disable and remove helpers when a layer is removed already).

**Comment by codeofsumit** [comment]
nevermind!

**Comment by codeofsumit** [comment]
if you want, try this branch and see if the `pm:remove` event works as expected for you
https://github.com/codeofsumit/leaflet.pm/pull/163

**Comment by GeoTob** [comment]
sorry mate, wanted to test this out and completely forgot :(

**Comment by codeofsumit** [comment]
@GeoTob no worries, it's merged now. Let me know if you have troubles with the latest release 👍

**Comment by GeoTob** [comment]
Thanks, will do!:)
