### ISSUE TITLE
Browser crashes when big GeoJSON files are enabled for editing

### ISSUE THREAD

**Issue by johnsoncherian** [codeofsumit/leaflet.pm#175]
Chrome and Firefox gets hanged when GeoJSON files with large number of `geometries` and `coordinates` are loaded as polygon layers for editing. Here is my code. `var layerObj = L.geoJSON(geojsonFeature).addTo(map); var options = { position: 'topleft', drawPolygon: true, editPolygon: true, deleteLayer: true }; map.pm.addControls(options); layerObj.pm.enable(options);`. I am including the GeoJSON data here. [geoJSON.txt](https://github.com/codeofsumit/leaflet.pm/files/1144766/geoJSON.txt)
Any Idea how to handle this.?

**Comment by codeofsumit** [comment]
Hi @johnsoncherian, I'll test this in the next days.

**Comment by codeofsumit** [comment]
Hi @johnsoncherian.
Your geojson is very, very dirty.
Just take a look at these small examples:
![image](https://user-images.githubusercontent.com/2399810/28315115-6d4357ae-6bbd-11e7-8227-4233597a86eb.png)
![image](https://user-images.githubusercontent.com/2399810/28315249-f82deeb0-6bbd-11e7-9720-4157dbfc397c.png)


Instead of a lines, these coast are "steps". Each step is a vertex and will create a marker. This results in hundreds of thousands (or even millions?) of markers on a map. This is simply a limitation of leaflet or browsers. Try putting a million DIVs on a page with even the tiniest bit of interactivity and the browser will crash as well.

I'm happy to do performance improvements, but you need to clean your data as well.

**Comment by johnsoncherian** [comment]
These GeoJSON layer defines political boundaries of a country. I cannot change it just like that. May be I'll have to look into some other API's like OpenLayers.?

**Comment by themre** [comment]
damn 15mb file? :) how many points does it contains? at our firm we have GWT topology editor and colleague optimized geometry editing by eliminating points that render close to each other (let's say if 30 points were present in 30x30 pixels, only 1 was rendered).
Leaflet can also render A LOT of points as SVG, but you need to take a look at the specs and you'll see that it uses simplify function that eliminates points before rendering otherwise it would also crash.

**Comment by codeofsumit** [comment]
@johnsoncherian of course I don't expect you to change a countries border ;-)
Just smooth out the data. I'm sure the border isn't zick-zack shaped like in the screenshots.
The border could also be drawn like this, then it'd be no problem.
![image](https://user-images.githubusercontent.com/2399810/28356484-8c279b34-6c68-11e7-8bbe-1fd17d3c2602.png)
![image](https://user-images.githubusercontent.com/2399810/28356510-9c7f6700-6c68-11e7-825b-3be221cfa044.png)
