### ISSUE TITLE
addLayer in Rectangle mode

### ISSUE THREAD

**Issue by mpalese** [codeofsumit/leaflet.pm#296]
Is it possible to create a layer by a L.geoJson function and with pm.enable function, modified it in rectangle mode???

**Comment by codeofsumit** [comment]
Hi @mpalese, no not right now.
Leaflet has a class L.Rectangle:
https://leafletjs.com/reference-1.3.0.html#rectangle

If your layers belong to that class, you should be able to edit it as a rectangle in leaflet.pm - if they're polygons inside a layerGroup they will be treated as a polygon.
I'd suggest you try to add them as a Rectangle to the map instead of GeoJSON and try again.

Let me know 👍
