### ISSUE TITLE
Listeners gone after cutting a layer

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/leaflet.pm#303]
As layers are redrawn after they're cut, event listeners on the original layer are lost and not on the new layers.

We should think about a solution here 🤔 

a) map all listeners of the original layer to all resulting layers
b) map all listeners of the original layer to only the first / biggest resulting layer
c) let them be lost

are there other options?

**Comment by cagritepebasili** [comment]
In my opinion, as layers are redrawn after they're cut, they're become different layer. However, since pm:cut event contains 'resultingLayers', anyone can pass the listeners to resultingLayers. As a result, I'd say 'let them be lost'.

**Comment by codeofsumit** [comment]
Let’s let them be lost until someone complains 😊

**Comment by shesellsanctuary** [comment]
I want to complain haha. 
I want to be able to get the layer independent of how many cuts were made to it. Because, if I have to create a new event for every new cut layer it will be a cascading hell :(  
I tried assigning the new layer to the same layer variable, but it does not work for some reason.

Can you help, please?

**Comment by Falke-Design** [comment]
Hi @shesellsanctuary,
I think we don't will changes this, because this now implemented for so long.

Here two workarounds:
**1. Assigne the same events on `pm:cut` which you assigne on `pm:create`:**

Change this:
```
map.on('pm:create',(e)=>{
... your events what you add to the created layer
```
to this:
```
map.on('pm:create pm:cut',(e)=>{
... your events what you add to the created layer
```
Now the same function is called if a new layer is created or cut

**2. re-add the old layer, set the new latlngs and remove the new one:**
The `_pmTempLayer` position is important else events like `pm:remove` and so called.
```
map.on('pm:cut',(e)=>{
    e.originalLayer.setLatLngs(e.layer.getLatLngs());
    e.originalLayer.addTo(map);
    e.originalLayer._pmTempLayer = false;

    e.layer._pmTempLayer = true;
    e.layer.remove();
})
```

**Comment by shesellsanctuary** [comment]
Thank you!
