### ISSUE TITLE
Recreate circles with GeoJSON

### ISSUE THREAD

**Issue by henev** [codeofsumit/leaflet.pm#346]
How do you recreate circles programmatically from GeoJSON?

```javascript
var mockupGeoJSON = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[54.311271,24.464211],[54.309384,24.46343],[54.311271,24.457336],[54.317961,24.458351],[54.323622,24.463039],[54.32225,24.469211],[54.318476,24.464367],[54.313158,24.463195],[54.311271,24.464211]]]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[54.411076,24.488053]}},{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[54.377692,24.454084],[54.36284,24.472558],[54.35522,24.467209],[54.345957,24.47799],[54.328117,24.465022],[54.333667,24.456268],[54.351618,24.454396],[54.358822,24.458772],[54.369112,24.447839],[54.377692,24.454084]]]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[54.398896,24.533567]}}]};
L.geoJSON(mockupGeoJSON).addTo(map);
```

In GeoJSON circles are represented as `"type":"Point"` and don't have radius. Is it possible to recreate a GeoJSON that has circles and polygons or I have to go with another approach?

**Comment by codeofsumit** [comment]
GeoJSON does not support Circles. And leaflet doesn't offer the necessary workarounds.

The workaround I use on [Geoman](https://geoman.io) to support circles is to store the radius in the GeoJSON properties and when parsing them to layers again, check for that property and turn it into circles instead of a marker then.
Details are in [this leaflet issue](https://github.com/Leaflet/Leaflet.draw/issues/390)

This has nothing to do with leaflet.pm though so I'm closing the issue ;-)

**Comment by henev** [comment]
Thanks for the fast response :)
