### ISSUE TITLE
Change cursor to "draggable" in circle edit mode

### ISSUE THREAD

**Issue by alisabondarev** [codeofsumit/leaflet.pm#356]
in L.PM.Edit.Line you have code to change the mouse cursor to "move":
if (this.options.draggable) {
            this._initDraggableLayer();
}

But on circle edit mode this line is missing

**Comment by codeofsumit** [comment]
it's because the circle is dragged differently. It's not dragged by moving the layer but by moving the center-vertex.
![layer move](https://user-images.githubusercontent.com/2399810/48603047-764cf300-e975-11e8-801e-0b30a778a473.gif)

I can see that this may be confusing. I will think about a solution to make this consistent - what would you prefer?

a) circle is moved like other layers from dragging anywhere on the shape
b) all layers have a "center marker" through which they can be moved
c) complete new controls to move and rotate (new feature)

**Comment by alisabondarev** [comment]
I like option 1

Or just change the mouse cursor to "move" on the center of the circle where
it is draggable right now.
