### ISSUE TITLE
Problem with leaflet-measure-path and dragging circles

### ISSUE THREAD

**Issue by Jumpy555** [codeofsumit/leaflet.pm#407]
Hi, dragging a circle, with the [leaflet-measure-path](https://github.com/ProminentEdge/leaflet-measure-path) library embedded, is firing an error:
this._layer.setLatLng(...) is undefined

http://jsfiddle.net/Jumpy/1bqtnLxj/

**Comment by codeofsumit** [comment]
Hi, based on previous issues I assume the problem is that leaflet-measure-paths overrides leaflet functions but does not return the instance - hence breaking method chaining.
I've created an issue in the repo:
https://github.com/ProminentEdge/leaflet-measure-path/issues/29

Here are the issues from the past for reference:
https://github.com/ProminentEdge/leaflet-measure-path/issues/11
https://github.com/ProminentEdge/leaflet-measure-path/issues/18

In essence, the fix should come from `leaflet-measure-path` as it's altering leaflet behaviour.

**Comment by Jumpy555** [comment]
Thank you!

**Comment by RobinBressan** [comment]
@codeofsumit Is it possible to publish a release include this fix on npm?

**Comment by codeofsumit** [comment]
@RobinBressan will come soon!
