### ISSUE TITLE
Add snapping when dragging shapes

### ISSUE THREAD

**Issue by tookun** [codeofsumit/leaflet.pm#427]
First of all, I love your work.
The snapping functionality is awesome but I was wondering if you could add snapping mode while in dragging mode.

e.g.: I have a rectangle with a specific dimension and want to move and snap it to an existing layer without changing the dimension.

**Comment by codeofsumit** [comment]
Hey there, nice feature indeed. Probably very complicated to do.
I'll add this as a feature-request until it has more upvotes.

**Comment by bumbummen99** [comment]
You can achieve that already by listening to 'pm:markerdragstart' and 'pm:markerdragend'. Although i have added an 'pm:markderdrag' event (#489) in order to update the snapped layers position. In order to find the snapped layers you have to filter the layers that should snap by the defined criteria and matching coordinates. There is probably a better way of achieving the desired behavior.
