### ISSUE TITLE
 Responsive does not draw the start line

### ISSUE THREAD

**Issue by aleffabricio** [codeofsumit/leaflet.pm#476]
Hello,

First of all, I would like to congratulate you on the plugin.

A question, In responsive mode when drawing a circle, rectangle, polygon does not appear the starting line.  Follow example below:

![Gif Mobile](https://user-images.githubusercontent.com/14118647/62079327-ddb98300-b224-11e9-80df-e0fd7489f857.gif)

OBS: 
This problem is related to so-called #263 ?

**Comment by codeofsumit** [comment]
The hintlines are drawn using mouseevents like mousemove. On touch-devices, there is no mouse (or no mouse events). That's why you can't see a line. It's like moving your thumb.

Now I can see that in your GIF, it should show the line but I'm also confused as to why you have a mouse on a touch device.
There should be no issue regarding responsiveness though. Resizing the browser will still work.

It would be great to get more info like Browser and Device and if the issue appears on http://leafletpm.now.sh

**Comment by aleffabricio** [comment]
Thanks for the answer, in this example i am using chrome `responsive` mode on the web for the mouse pointer appear. When I emulated on my phone, it was in a webview where I had the same result shown in gif.

![teste](https://user-images.githubusercontent.com/14118647/63692504-32322d00-c7e8-11e9-8d3e-ce012f3096a2.gif)

**Comment by codeofsumit** [comment]
Ah got it. Ok, that's because it's touch mode. Imagine doing this on your phone, there is nothing to connect the line to because I can't know where your thumb is until you touch it ;-)

**Comment by aleffabricio** [comment]
yes I understand, thank you very much for the reply.
