### ISSUE TITLE
Unable to Remove Last Point from Polygon

### ISSUE THREAD

**Issue by tdaubs** [codeofsumit/leaflet.pm#48]
After drawing out a polygon, if you want to remove it... you can remove all points except the last one.

Also, it would be great to see some functionality for deleting an entire polygon with one action as opposed to a point by point removal approach.

Nevertheless, nice work so far!

**Comment by codeofsumit** [comment]
Thanks for the feedback. I'm going to add a delete function to remove the entire polygon.

**Comment by codeofsumit** [comment]
@tdaubs the possibility to remove the last point from the polygon will be in the release today or tomorrow.
A new button in the toolbar (Removal Tool) is also added but turned off because of missing icons.
I'll enable this and other new toolbar features in an upcoming release once I found some proper icons I can use without getting sued 😉

**Comment by codeofsumit** [comment]
The fix for deleting the last marker is now available on bower and npm

**Comment by tdaubs** [comment]
Thanks for the update! Very good work!
