### ISSUE TITLE
Dreaming of a reshape feature tool

### ISSUE THREAD

**Issue by agh69** [codeofsumit/leaflet.pm#485]
Hi,

As mentioned in another thread, it would be a dream to have a reshape polygon tool in leaflet.pm, similar to QGIS's Reshape feature-tool in the Advance Digitizing toolbar. The tool allows one to edit the shape of polygons without having to drag individual nodes one by one. Or even to display them - saving situations where there a 1000+ nodes slowing down computers. Depending on if you start outside or inside a polygon it will either decrease or make the polygon bigger. The new boarder will be where you have drawn the line. It is soooo helpful in QGIS and would be so here as well.  Unfortunately, my skills in terms of developing stops at suggesting this as a future tool. :( 

![reshape_tool_qgis2](https://user-images.githubusercontent.com/52559551/63958559-e18e2e80-ca8a-11e9-9d2e-552ff3aa38ff.gif)

**Comment by codeofsumit** [comment]
thinking about how to approach this right now. Can you clarify if this thinking is correct?

Let's say I draw the "reshape" line:

- start and end of line are inside a polygon: the shape is additive (is added to the polygon)
- start and end of line are outside of polygon: the shape is substracting (is removed from the polygon)
- The combination of the two results in adjacent polygon borders to be "moved", which is awesome!

But what happens when you draw a line that starts inside Polygon A and ends in Polygon B? I can't see that example in the gif and I'm unsure about the desired result 🤔

**Comment by agh69** [comment]
I think it's like this: You can start in polygon A and end in polygon B, but only the drawings when you cross a polygon's border more than once counts. If you only cross the border once, it will be invalid editing and nothing happens. You can even start in polygon A and end in polygon C without a single click in polygon B, but since you cross B's border twice (from "outside") it will perform cutting of B. Here area a few more gifs: 


![reshape_feature1](https://user-images.githubusercontent.com/52559551/66104831-11fd4700-e5ba-11e9-8d86-82ff5be7343b.gif)
![reshape_feature4](https://user-images.githubusercontent.com/52559551/66104985-6f919380-e5ba-11e9-81dc-4e68ef17d7dc.gif)
![reshape_feature5](https://user-images.githubusercontent.com/52559551/66105023-98b22400-e5ba-11e9-9a09-82f3c79c05eb.gif)

**Comment by codeofsumit** [comment]
To Answer once implemented:
https://stackoverflow.com/questions/57690066/how-to-make-adjacent-polygons-align-with-the-edited-polygon-in-leaflet
