### ISSUE TITLE
Is there any way I can create arrow?

### ISSUE THREAD

**Issue by ZHANGLUInfinite** [codeofsumit/leaflet.pm#487]
![InkedF03EEE4B44F0094CB85629D6AE0F6263_LI](https://user-images.githubusercontent.com/50860184/64089131-383f8500-cd77-11e9-800c-e4594636f23b.jpg)

**Comment by codeofsumit** [comment]
Not like that, no as it's not a geo-shape afaik.

**Comment by dennisat** [comment]
Hey, first of all, thanks for this awesome library.

While lines with arrows may not be considered a traditional geo shape, they are definitely handy for maps because they show directions. Adding such a feature would be really cool and practical. It would allow users to easily depict movement or flow in a particular direction on their maps.

Would it be possible to add it?
