### ISSUE TITLE
Expose an additional event before and after a polygon gets deleted

### ISSUE THREAD

**Issue by felixheck** [codeofsumit/leaflet.pm#91]
Hi there.

There are several pm-custom events including `created`, `edited` and `dragXYZ`.
AFAIK there are no events which get triggered when a polygon gets deleted. On the one hand it would be nice to ask for confirmation (like a `pm:deletestart` event) and on the other hand I would like to send a request after the polygon was deleted (like a `pm:deleteend` event).

thanks :)

**Comment by codeofsumit** [comment]
ok I've thought about this.

The problem is, deleting a layer isn't a function of leaflet.pm. I just provide a button in the toolbar that enables a click event per layer and deletes it.

Deleting a layer is a very simple functionality of leaflet. So you can do this:

`layer.remove()` to remove a layer from the map.

Now delete a layer via click:
`layer.on('click', function() { layer.remove(); });`

With a desired confirmation:
```
layer.on('click', function() { 
  var delete = confirm('Are you sure you want to delete this layer?');
  if(delete) {
    layer.remove(); 
  }
});
```

You can listen to the removal via leaflets [built-in remove event](http://leafletjs.com/reference-1.0.0.html#layer-remove).
`layer.on('remove', function() { // your callback code });`

You can also listen to the [layerremove event on the map](http://leafletjs.com/reference-1.0.0.html#map-layerremove) to know whenever any layer gets removed from the map.

**Comment by felixheck** [comment]
Thanks! @codeofsumit
